#include "UF_API.h"
#include "UF_SysParameter.h"
#include "mbed.h"

//
// Static variables
//

SysParameter s_SysParameter[] =
{
    { UF_SYS_TIMEOUT, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ENROLL_MODE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_SECURITY_LEVEL, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ENCRYPTION_MODE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_SENSOR_TYPE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_IMAGE_FORMAT, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_MODULE_ID, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_FIRMWARE_VERSION, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_SERIAL_NUMBER, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_BAUDRATE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_AUX_BAUDRATE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ENROLLED_FINGER, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_AVAILABLE_FINGER, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_SEND_SCAN_SUCCESS, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ASCII_PACKET, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ROTATE_IMAGE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_SENSITIVITY, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_IMAGE_QUALITY, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_AUTO_RESPONSE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_NETWORK_MODE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_FREE_SCAN, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_PROVISIONAL_ENROLL, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_PASS_WHEN_EMPTY, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_RESPONSE_DELAY, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_MATCHING_TIMEOUT, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_BUILD_NO, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ENROLL_DISPLACEMENT, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_TEMPLATE_SIZE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ROTATION, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_LIGHTING_CONDITION, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_FREESCAN_DELAY, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_CARD_ENROLL_MODE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_FAST_MODE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_WATCHDOG, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_TEMPLATE_TYPE, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_ENHANCED_PRIVACY, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_FAKE_DETECT, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_CHECK_LATENT, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_VOLTAGE_WARNING, UF_SYS_PARAMETER_NOT_READ },
    { UF_SYS_POWEROFF_TIMEOUT, UF_SYS_PARAMETER_NOT_READ },
    { -1, 0 },
};

SysParameter* GetSysParamPointer(void)
{
    return s_SysParameter;
}

/**
 *  Initialize system parameter
 */
void UF_InitSysParameter(void)
{
    UF_RET_CODE result;
    int i = 0;

printf("\r[andro.yoon] %s\n", __func__);
    while( s_SysParameter[i].parameter != -1 )
    {
 printf("\r[andro.yoon] s_SysParameter[%02d].parameter = 0x%02X\n", i, s_SysParameter[i].parameter);
        s_SysParameter[i++].value = UF_SYS_PARAMETER_NOT_READ;
    }
}
